export enum HttpStatus {
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NO_CONTENT = 204,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    METHOD_NOT_ALLOWED = 405,
    CONFLICT = 409,
    UNPROCESSABLE_ENTITY = 422,
    INTERNAL_SERVER_ERROR = 500,
    NOT_IMPLEMENTED = 501,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
}

export const statusCodeNames: Record<HttpStatus, string> = {
    [HttpStatus.OK]: "OK",
    [HttpStatus.CREATED]: "Created",
    [HttpStatus.ACCEPTED]: "Accepted",
    [HttpStatus.NO_CONTENT]: "No content",
    [HttpStatus.BAD_REQUEST]: "Bad request",
    [HttpStatus.UNAUTHORIZED]: "Unauthorized",
    [HttpStatus.FORBIDDEN]: "Forbidden",
    [HttpStatus.NOT_FOUND]: "Not found",
    [HttpStatus.METHOD_NOT_ALLOWED]: "Method not allowed",
    [HttpStatus.CONFLICT]: "Conflict",
    [HttpStatus.UNPROCESSABLE_ENTITY]: "Unprocessable entity",
    [HttpStatus.INTERNAL_SERVER_ERROR]: "Internal server error",
    [HttpStatus.NOT_IMPLEMENTED]: "Not implemented",
    [HttpStatus.BAD_GATEWAY]: "Bad gateway",
    [HttpStatus.SERVICE_UNAVAILABLE]: "Service unavailable",
};
